"""add user_id to outfits

Revision ID: 80c2334b9c61
Revises: db694e9f6b84
Create Date: 2025-01-09 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80c2334b9c61"
down_revision: Union[str, Sequence[str], None] = "db694e9f6b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outfits", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "outfits", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "outfits", type_="foreignkey")
    op.drop_column("outfits", "user_id")
    # ### end Alembic commands ###
